### ISSUE TITLE
Unable to Access fstogendata-ext Data via gsutil

### ISSUE THREAD

**Issue by GuohuiGuan** [twosigma/functional_semantic_types#2]
Dear Project Team,  

Thank you for the work you’ve done with this project!

I encountered a small issue when trying to follow the steps under **Table Download** to retrieve the data from the bucket `gs://fstogendata-ext`. Upon running the following command:

```
gsutil -m cp gs://fstogendata-ext/approved/REQSEC-61982/2024-08-16-labs-fst-datasets-2.tar _temp.tar
```

I received the following error message:

```
AccessDeniedException: 403 HttpError accessing https://storage.googleapis.com/download/storage/v1/b/fstogendata-ext/o/approved%2FREQSEC-61982%2F2024-08-16-labs-fst-datasets-2.tar?generation=1724896698249446&alt=media&userProject=fst-dev-project: response: <{'status': '403'}>, content <The billing account for the owning project is disabled in state absent>
```

It appears that the **billing account associated with the owning project** of the storage bucket has been disabled, preventing access to the data even though I am specifying a valid billing project using `--billing-project`. Since the bucket uses **Requester Pays**, I am unable to proceed with downloading the datasets needed for the workflow.

Could you kindly assist in resolving this issue? It would be helpful to verify the billing account associated with the bucket’s project (`fstogendata-ext`) and ensure it is active.

Thank you very much for your support and for this contribution!

Best regards,  
Hui

**Comment by SachinKonan** [comment]
Hi hui, can you try running the same command using `gcloud storage`? It seems like user-defined billing project's aren't enabled, per [this source](https://stackoverflow.com/questions/78023179/how-can-a-billing-project-be-stated-in-googles-command-line-tool-gsutil-cp-on).

Let me know if that works

**Comment by GuohuiGuan** [comment]
Yeah! That works! Thank you!
